### ISSUE TITLE
Visually differentiate the 'Peek Panels' for Active/Dead messages

### ISSUE THREAD

**Issue by lukeschafer** [GlobalX/SbManager#28]
They look the same.. maybe just the glyph in the header will do, but it could also be a colour change

**Comment by drewfreyling** [comment]
![sbmanager icons](https://cloud.githubusercontent.com/assets/1145869/11945072/7003d13e-a897-11e5-8a12-738e2f67ce29.png)
Do you think the icons the header is visually differentiated enough?

**Comment by lukeschafer** [comment]
maybe the colours from the overview panels too?

**Comment by drewfreyling** [comment]
Ok sounds like a good idea. I'll have to update the home page screenshots too once I PR it.
