### ISSUE TITLE
Fix appveyor

### ISSUE THREAD

**Issue by lukeschafer** [GlobalX/SbManager#45]
I believe it's red because of the assemblyversion

On appveyor, in settings under 'General', scroll down and make it look like this:

![image](https://cloud.githubusercontent.com/assets/980396/9054605/8aa1c13e-3ac6-11e5-8c16-acbd10504e68.png)

**Comment by drewfreyling** [comment]
Is this still an issue @lukeschafer

**Comment by lukeschafer** [comment]
Nope

**Comment by brucem** [comment]
Closing
