### ISSUE TITLE
Display "Scheduled Count" in 'Overview" view

### ISSUE THREAD

**Issue by ricjac** [GlobalX/SbManager#53]
Currently only the "Active Messages" and "Dead Letters" are displayed in the 'Overview'. 
It would be a nice feature to also have the "Scheduled Count" displayed, as it is displayed when you drill down on individual queues.

**Comment by lukeschafer** [comment]
Currently the overview uses the blue for 'active' which is the same blue as the 'scheduled' on the entity screen. If this change is made, the colours should probably align

**Comment by drewfreyling** [comment]
This is a good idea and we should find a new colour for scheduled. Feel free to submit a PR for this one @ricjac

**Comment by ricjac** [comment]
Good point @lukeschafer 
I will take a look if I get time, but consider it 'up for grabs'

**Comment by ricjac** [comment]
Done

**Comment by drewfreyling** [comment]
#57 says it is only part 1, was there anything else or should I consider this closed?

**Comment by ricjac** [comment]
@drewfreyling I forgot to mention that part 2 was the second commit.
